name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '27'
          gleam-version: '1.5.1'
          rebar3-version: '3'
      - run: gleam format --check src test
      - run: gleam deps download
      - run: gleam test
